server:
  port: 8082
spring:
  datasource:
    username: root
    password: root
    jdbc-url: jdbc:mysql://localhost:3306/d_score?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-score

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
ribbon:
  eureka:
    enabled: true

tcc:
  transaction:
    table-name: t_transaction
    datasource:
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/d_transaction?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
    recovery:
      quartz:
        enable: false


      


    
